### ISSUE TITLE
Ergänzung: verschiedenes von felixx

### ISSUE THREAD

**Issue by erdkinder** [phranck/Amazon-Alternativen#28]
Hier ein paar kleine, aber feine Vorschläge:

[Steinehelden](https://steinehelden.de) LEGO-Shop der Lebenshilfe Westpfalz. 
Arbeitsplätze für Menschen mit Beeinträchtigungen.

[Drax Mühle](https://shop.drax-muehle.de) Eine feine kleine Mühle bei mir ums Eck, für Mehl, Getreide und Zubehör. 
Regional und auch mit Bio-Sortiment.

[Second IT Store](https://second-it-store.de) Shop für gebrauchte IT, viele Lenovo und HP Laptops, aber auch immer anderes wie Iphones. 
Wir haben mit ihnen unsere Schule ausgestattet.

**Comment by phranck** [comment]
@erdkinder Vielen Dank fuer diese Ergaenzungen. Diese "Drax Muehle": Wo ist "bei ums Eck"?

**Comment by erdkinder** [comment]
Ja, das hätte ich hinzufügen können: 20km etwa von mir zuhause entfernt. Östlich von München. Da sie einen Online-Shop haben, kann man das "bei mir ums Eck" in deiner Liste ja auch komplett weglassen.

**Comment by erdkinder** [comment]
Beim Durchschauen der Liste ist mir noch ein Wekzeugshop eingefallen:

[https://www.dictum.com](Hochwertiges Werkzeug; Spezialist für japanische Sägen und Messer)

**Comment by phranck** [comment]
Wie konnte ich die nur vergessen! Hab schon selbst bei denen gekauft. 😃
