### ISSUE TITLE
Ergänzung: == Feine-Werkzeuge.de ==

### ISSUE THREAD

**Issue by haterakathegrinch1** [phranck/Amazon-Alternativen#32]
* [Feine-Werkzeuge.de](https://www.feine-werkzeuge.de)
* (Hochwertige Handwerkzeuge,v.a. zur Holzbearbeitung)
* Mittelständler, sehr guter Service, derzeit die besten Profiwerkzeuge am Markt, bis jetzt immer sehr gute Erfahrungen gemacht. Leider nicht billig.

**Comment by kuro-codes** [comment]
Hier scheint dass SSL Zertifikat abgelaufen zu sein. Weiß nicht ob ein Shop ohne richtig funktionierendes SSL so nice ist.

**Comment by haterakathegrinch1** [comment]
Ah,ein Fehler meinerseits, muss https://www.feinewerkzeuge.de sein,nicht mit - in der Mitte.
