### ISSUE TITLE
Fairafric

### ISSUE THREAD

**Issue by Ragnaroek8** [phranck/Amazon-Alternativen#38]
Trage hier bitte deine(n) Vorschlag/Vorschläge ein. Sie sollten folgende Dinge enthalten:

*[Fairafric](https://fairafric.com/collections/produkte)(Bieten Schokolade, für die nicht nur faire Löhne an Kakaobauern gezahlt wird, sondern die zudem auch komplett in Ghana produziert wird. Komplette Wertschöpfungskette dort.)

**Comment by moschlar** [comment]
Siehe #2
