### ISSUE TITLE
Meta-Listen

### ISSUE THREAD

**Issue by Alex-Esko** [phranck/Amazon-Alternativen#39]
Macht es Sinn Meta-Listen aufzunehmen?

Diese umfangreichen Listen von Mikrocontroller.net sind zwar nicht immer ganz aktuell, aber frei von Spam oder unseriösen Anbietern: 
* 150 [Elektronikversender](https://www.mikrocontroller.net/articles/Elektronikversender)
* 33 [Eisenwarenversender](https://www.mikrocontroller.net/articles/Eisenwarenversender), dazu 9 Kunststoffversender und 17 Maßanfertiger

**Comment by phranck** [comment]
Hm... Joa, warum eigentlich nicht?
Ich machma.
